# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SnapshotTests' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SnapshotTests
  pod 'SnapshotTesting', '~> 1.7.2'

  target 'SnapshotTestsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
